apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: holaweb-primary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3333
  selector:
    app: hola-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
