apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: holaapp-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-primary
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hola-primary
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: holaweb-canary
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/name: holaweb-primary
        app.kubernetes.io/part-of: hola-app
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: version=0.1.0 revision=1 releasename=hola-app-staging-holaweb keptn_project=hola-app
            keptn_service=holaweb keptn_stage=staging keptn_deployment=primary
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: KEPTN_PROJECT
          value: holaweb
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEPTN_SERVICE
          value: holaweb
        - name: UNLEASH_SERVER_URL
          value: http://unleash.unleash-dev/api
        image: 10.250.1.101:5000/hello-world-nodejs
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 3333
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        name: holaweb
        ports:
        - containerPort: 3333
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3333
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
status: {}
